SCSIDevice (linux): do_platform_cmd(): unwrap direction in one go while also fixing future compilation error
warning[E0503]: cannot use `*dir` because it was mutably borrowed
  --> src/scsi/linux.rs:69:5
   |
57 |         let mut data = if let Direction::From(buf) = dir {
   |                                               --- borrow of `dir.0` occurs here
...
69 |                 Direction::None => -1,
   |                 ^^^^^^^^^^^^^^^ use of borrowed `dir.0`
...
73 |             dxferp:    match data {
   |                              ---- borrow later used here
   |
   = warning: this error has been downgraded to a warning for backwards compatibility with previous releases
   = warning: this represents potential undefined behavior in your code and this warning will become a hard error in the future